# Generated by Django 5.2.9 on 2026-01-11 00:01

import core.models
import django.core.serializers.json
import django.db.models.deletion
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import types
import typing
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(choices=[('gemini', 'Gemini'), ('whisper.cpp', 'Whisper.cpp')], max_length=20)),
                ('host', models.CharField(blank=True, default='', max_length=255)),
                ('is_preset', models.BooleanField(default=False)),
                ('input_price', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('output_price', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
            },
        ),
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guid', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('source_audio_url', models.URLField(blank=True, default='', max_length=500)),
                ('ads', django_pydantic_field.fields.PydanticSchemaField(config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(list, (core.models.PodcastEpisodeAdvert,)))),
                ('transcription', django_pydantic_field.fields.PydanticSchemaField(config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(list, (core.models.TranscriptionSegment,)))),
            ],
        ),
        migrations.CreateModel(
            name='PodcastShow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('itunes_id', models.CharField(max_length=100, unique=True)),
                ('source_rss_url', models.URLField(max_length=500)),
                ('path_directory', models.CharField(max_length=500)),
                ('has_ads', models.BooleanField()),
                ('initial_sync_completed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gemini_api_key', models.CharField(blank=True, default='', max_length=255)),
                ('analysis_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_configs', to='core.aimodel')),
                ('transcription_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcription_configs', to='core.aimodel')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configuration',
            },
        ),
        migrations.CreateModel(
            name='ClippingReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('transcribed_at', models.DateTimeField(blank=True, null=True)),
                ('analysed_at', models.DateTimeField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('logs', models.TextField(blank=True, default='')),
                ('exceptions', django_pydantic_field.fields.PydanticSchemaField(config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(list, (str,)))),
                ('transcription', django_pydantic_field.fields.PydanticSchemaField(config=None, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, schema=django_pydantic_field.compat.django.GenericContainer(typing.Union, (core.models.TranscriptionReport, types.NoneType)))),
                ('analysis', django_pydantic_field.fields.PydanticSchemaField(config=None, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, schema=django_pydantic_field.compat.django.GenericContainer(typing.Union, (core.models.AnalysisReport, types.NoneType)))),
                ('analysis_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_reports', to='core.aimodel')),
                ('transcription_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcription_reports', to='core.aimodel')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clipping_reports', to='core.podcastepisode')),
            ],
            options={
                'verbose_name': 'Clipping Report',
                'verbose_name_plural': 'Clipping Reports',
                'ordering': ['-queued_at'],
            },
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='core.podcastshow'),
        ),
        migrations.AlterUniqueTogether(
            name='podcastepisode',
            unique_together={('podcast', 'guid')},
        ),
    ]
