"""add retention policies

Revision ID: 395988822d5f
Revises: a1f2c3d4e5b6
Create Date: 2026-09-16 18:11:34.135132

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op


revision: str = "395988822d5f"
down_revision: str | None = "a1f2c3d4e5b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    with op.batch_alter_table("podcast_episodes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("clip_source", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True)
        )

    # server_default true backfills existing rows to the Mixed default (keep
    # manual clips). The model carries no server default, but the drift guard
    # does not compare server defaults, so this is not flagged.
    with op.batch_alter_table("podcast_shows", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "keep_manual_clips",
                sa.Boolean(),
                nullable=False,
                server_default=sa.true(),
            )
        )

    _apply_retention_profiles()


LIVE_TITLES = (
    "The Athletic FC Podcast",
    "The View From The Lane",
    "Football Weekly",
    "Libero",
    "The Totally Football Show with James Richardson",
    "Tifo Football Podcast",
)

ARCHIVE_TITLES = (
    "For Our Sins: The Clichés Pod Archive",
    "The Kitchen Cabinet",
    "It Was What It Was: The Football History Podcast",
    "Acquired",
)

MIXED_TITLES = (
    "Football Clichés",
    "The Pragmatic Engineer",
)


def _apply_retention_profiles() -> None:
    """Set per-podcast retention profiles for existing deployments (MY-185).

    Live keeps the newest N clipped episodes regardless of source.
    Mixed keeps manual clips and the newest N automatic clips.
    Archive disables automatic cleanup entirely.
    """
    from sqlalchemy import bindparam
    from sqlalchemy import text

    conn = op.get_bind()

    # Live: manual clips are cleanup candidates. Preserve existing counts
    # (e.g. Football Weekly's keep newest 3); default to 5 where unset.
    conn.execute(
        text(
            "UPDATE podcast_shows SET keep_manual_clips = 0 WHERE " + "title IN :titles"
        ).bindparams(bindparam("titles", expanding=True)),
        {"titles": list(LIVE_TITLES)},
    )
    conn.execute(
        text(
            "UPDATE podcast_shows SET cleanup_keep_count = 5 WHERE "
            + "title IN :titles AND cleanup_keep_count IS NULL"
        ).bindparams(bindparam("titles", expanding=True)),
        {"titles": list(LIVE_TITLES)},
    )

    # Mixed: protect manual clips, default to newest 5 automatic.
    conn.execute(
        text(
            "UPDATE podcast_shows SET keep_manual_clips = 1 WHERE " + "title IN :titles"
        ).bindparams(bindparam("titles", expanding=True)),
        {"titles": list(MIXED_TITLES)},
    )
    conn.execute(
        text(
            "UPDATE podcast_shows SET cleanup_keep_count = 5 WHERE "
            + "title IN :titles AND cleanup_keep_count IS NULL"
        ).bindparams(bindparam("titles", expanding=True)),
        {"titles": list(MIXED_TITLES)},
    )

    # Existing Mixed clips cannot have their source reconstructed, so mark
    # every clipped episode manual to protect existing files.
    conn.execute(
        text(
            "UPDATE podcast_episodes SET clip_source = 'manual' WHERE "
            + "podcast_id IN (SELECT id FROM podcast_shows WHERE title IN :titles) "
            + "AND id IN (SELECT episode_id FROM clipping_reports "
            "WHERE edited_at IS NOT NULL)"
        ).bindparams(bindparam("titles", expanding=True)),
        {"titles": list(MIXED_TITLES)},
    )

    # Archive: disable automatic cleanup. Files already removed stay removed.
    conn.execute(
        text(
            "UPDATE podcast_shows SET keep_manual_clips = 1, "
            + "cleanup_keep_count = NULL, cleanup_keep_days = NULL WHERE "
            + "title IN :titles"
        ).bindparams(bindparam("titles", expanding=True)),
        {"titles": list(ARCHIVE_TITLES)},
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("podcast_shows", schema=None) as batch_op:
        batch_op.drop_column("keep_manual_clips")

    with op.batch_alter_table("podcast_episodes", schema=None) as batch_op:
        batch_op.drop_column("clip_source")

    # ### end Alembic commands ###
