"""baseline schema

Revision ID: 3c1649611245
Revises:
Create Date: 2026-05-25 22:55:44.223383

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

revision: str = "3c1649611245"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_providers",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("api_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("base_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "podcast_shows",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("itunes_id", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("source_rss_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("path_directory", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("has_ads", sa.Boolean(), nullable=False),
        sa.Column("clip_mode", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("initial_sync_completed", sa.Boolean(), nullable=False),
        sa.Column("cleanup_keep_days", sa.Integer(), nullable=True),
        sa.Column("cleanup_keep_count", sa.Integer(), nullable=True),
        sa.Column("custom_prompt", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("itunes_id"),
    )
    op.create_table(
        "ai_models",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("provider_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("supports_transcription", sa.Boolean(), nullable=False),
        sa.Column("supports_analysis", sa.Boolean(), nullable=False),
        sa.Column("input_price", sa.Float(), nullable=False),
        sa.Column("output_price", sa.Float(), nullable=False),
        sa.Column("context_window", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["ai_providers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_id", "name", name="uq_ai_model_provider_name"),
    )
    op.create_table(
        "podcast_episodes",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("podcast_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("guid", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("source_audio_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("stored_filename", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("cleaned_at", sa.DateTime(), nullable=True),
        sa.Column("ad_breaks", sa.Text(), nullable=True),
        sa.Column("transcription", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["podcast_id"],
            ["podcast_shows.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=False,
    )
    op.create_table(
        "clipping_reports",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("episode_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("transcription_model_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("analysis_model_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("queued_at", sa.DateTime(), nullable=False),
        sa.Column("downloaded_at", sa.DateTime(), nullable=True),
        sa.Column("transcribed_at", sa.DateTime(), nullable=True),
        sa.Column("analysed_at", sa.DateTime(), nullable=True),
        sa.Column("edited_at", sa.DateTime(), nullable=True),
        sa.Column("logs", sa.Text(), nullable=True),
        sa.Column("exceptions", sa.Text(), nullable=True),
        sa.Column("transcription_report", sa.Text(), nullable=True),
        sa.Column("analysis_report", sa.Text(), nullable=True),
        sa.Column("celery_task_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_model_id"],
            ["ai_models.id"],
        ),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["podcast_episodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transcription_model_id"],
            ["ai_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "config",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("transcription_model_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("analysis_model_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("keep_raw_episodes", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_model_id"],
            ["ai_models.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transcription_model_id"],
            ["ai_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("config")
    op.drop_table("clipping_reports")
    op.drop_table("podcast_episodes")
    op.drop_table("ai_models")
    op.drop_table("podcast_shows")
    op.drop_table("ai_providers")
    # ### end Alembic commands ###
