"""add episode image_url

Revision ID: 7b7b36cd579a
Revises: 3e51d4cf1bd8
Create Date: 2026-06-01 21:28:08.700106

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op


revision: str = "7b7b36cd579a"
down_revision: str | None = "3e51d4cf1bd8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("podcast_episodes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("image_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("podcast_episodes", schema=None) as batch_op:
        batch_op.drop_column("image_url")

    # ### end Alembic commands ###
